-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.315.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2019/3/8 11:26:07
-- Server version: 5.5.28
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE company_business;

--
-- Definition for table tomato_activity_banner
--
CREATE TABLE tomato_activity_banner (
  id VARCHAR(64) NOT NULL COMMENT 'ID',
  image_url VARCHAR(255) DEFAULT NULL COMMENT 'banner图片下载链接',
  name VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '类别名称',
  sub_name VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '副标题',
  belong VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '属于模块',
  status TINYINT(1) UNSIGNED DEFAULT 1 COMMENT '类别状态1-正常,2-已废弃',
  sort_order INT(4) DEFAULT NULL COMMENT '排序编号,同类展示顺序,数值相等则自然排序',
  create_by VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '创建人',
  create_id VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '创建人ID',
  create_date DATE DEFAULT NULL COMMENT '创建时间',
  update_by VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '最近操作人',
  update_id VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '最后操作人ID',
  update_date DATE DEFAULT NULL COMMENT '更新时间',
  del_flag TINYINT(1) DEFAULT 0 COMMENT '删除标记',
  remarks VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '备注信息',
  version INT(11) DEFAULT 0 COMMENT 'api版本号',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
COMMENT = '活动配置banner表';

--
-- Definition for table tomato_award_config
--
CREATE TABLE tomato_award_config (
  id VARCHAR(64) NOT NULL COMMENT '主键',
  award_limit INT(11) DEFAULT NULL COMMENT '运营限制兑换触发条件',
  gold DECIMAL(10, 1) DEFAULT 1.0 COMMENT '如一致可设置rate',
  status TINYINT(1) DEFAULT 1 COMMENT '类别状态1-正常,0-停用',
  sort_order INT(4) NOT NULL AUTO_INCREMENT COMMENT '排序编号,同类展示顺序,数值相等则自然排序',
  create_by VARCHAR(64) DEFAULT 'NULL' COMMENT '创建者ID',
  create_id VARCHAR(64) DEFAULT 'NULL' COMMENT '创建者',
  create_date DATETIME DEFAULT NULL COMMENT '创建时间',
  update_by VARCHAR(64) DEFAULT 'NULL' COMMENT '更新者ID',
  update_id VARCHAR(64) DEFAULT 'NULL' COMMENT '最后修改者',
  update_date DATETIME DEFAULT NULL COMMENT '更新时间',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标记（0：正常；1：删除）',
  remarks VARCHAR(255) DEFAULT 'NULL' COMMENT '备注信息',
  PRIMARY KEY (id),
  INDEX order_num (sort_order)
)
ENGINE = INNODB
AUTO_INCREMENT = 6
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '奖励兑换限制表';

--
-- Definition for table tomato_cart_info
--
CREATE TABLE tomato_cart_info (
  id VARCHAR(64) NOT NULL COMMENT 'ID',
  user_name VARCHAR(64) NOT NULL COMMENT '微信openId',
  product_id VARCHAR(64) NOT NULL COMMENT '商品ID',
  quantity INT(11) UNSIGNED DEFAULT NULL COMMENT '数量',
  checked TINYINT(1) DEFAULT 1 COMMENT '是否选择,1=已勾选,0=未勾选',
  create_by VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '创建人',
  create_id VARCHAR(64) DEFAULT NULL COMMENT '创建人ID',
  create_date DATETIME DEFAULT NULL COMMENT '创建时间',
  update_by VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '最近操作人',
  update_id VARCHAR(64) DEFAULT NULL COMMENT '最后操作人ID',
  update_date DATETIME DEFAULT NULL COMMENT '更新时间',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标记（0：正常；1：删除）',
  remarks VARCHAR(255) DEFAULT NULL COMMENT '备注信息',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
COMMENT = '购物车表';

--
-- Definition for table tomato_gold_log
--
CREATE TABLE tomato_gold_log (
  id VARCHAR(64) NOT NULL COMMENT 'id',
  user_name VARCHAR(64) DEFAULT NULL COMMENT 'openid',
  event VARCHAR(64) DEFAULT NULL COMMENT '当前金币变化的事件类型1：步数兑换番茄币 2：番茄币兑换商品',
  gold_type VARCHAR(64) DEFAULT '1' COMMENT '金币的变化类别1：增加 2：减少',
  gold_date DATETIME DEFAULT NULL COMMENT '用户兑换时间',
  gold DECIMAL(10, 2) DEFAULT 0.00 COMMENT '本次兑换获得的金币',
  step INT(11) DEFAULT 0 COMMENT '使用步数',
  remark VARCHAR(255) DEFAULT NULL COMMENT '预留字段',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '金币兑换日志表';

--
-- Definition for table tomato_order_info
--
CREATE TABLE tomato_order_info (
  id VARCHAR(64) NOT NULL COMMENT 'ID',
  gold DECIMAL(20, 2) DEFAULT 0.00 COMMENT '实际付款金币',
  product_id_two VARCHAR(64) DEFAULT NULL COMMENT '商品id',
  order_id VARCHAR(64) DEFAULT NULL COMMENT '系统生成的自定义订单号',
  user_name VARCHAR(64) DEFAULT NULL COMMENT '用户ID,查询到username',
  shipping_id VARCHAR(64) DEFAULT NULL COMMENT '收货人ID',
  total_gold DECIMAL(20, 2) DEFAULT NULL COMMENT '商品总金币',
  total_price DECIMAL(20, 2) DEFAULT NULL COMMENT '商品总价',
  quantity INT(11) DEFAULT 1 COMMENT '商品数量',
  price DECIMAL(20, 2) DEFAULT NULL COMMENT '实际付款金额,单位是元,保留两位小数',
  payment_type INT(4) NOT NULL DEFAULT 1 COMMENT '支付类型,1-在线支付',
  postage DECIMAL(20, 2) DEFAULT NULL COMMENT '运费,单位是元',
  status_two INT(10) DEFAULT 0 COMMENT '订单状态:0-待发货-1-已发货，2-已签收，3-取消订单',
  payment_time DATETIME DEFAULT NULL COMMENT '支付时间',
  send_time DATETIME DEFAULT NULL COMMENT '发货时间',
  end_time DATETIME DEFAULT NULL COMMENT '交易完成时间',
  create_date_two DATETIME DEFAULT NULL COMMENT '下单时间',
  update_date DATETIME DEFAULT NULL COMMENT '更新时间',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标记（0：正常；1：删除）',
  remarks VARCHAR(100) DEFAULT NULL COMMENT '备注信息',
  wx_order_no VARCHAR(64) DEFAULT NULL COMMENT '微信订单号',
  express_company INT(11) DEFAULT 0 COMMENT '物流公司:0-顺丰快递,1-中国邮政,2-中通快递,3-韵达快递,4-圆通速递,5-申通快递,6-京东快递,7-百世快递,8-联邦快递,9-天天快递',
  express_no VARCHAR(64) DEFAULT NULL COMMENT '快递编号',
  shipments TINYINT(4) DEFAULT 0 COMMENT '""',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
COMMENT = '订单表';

--
-- Definition for table tomato_packet_config
--
CREATE TABLE tomato_packet_config (
  id VARCHAR(64) NOT NULL COMMENT '主键',
  packet_count INT(9) DEFAULT NULL COMMENT '红包奖励次数',
  award INT(11) DEFAULT 2000 COMMENT '配置步数奖励',
  description VARCHAR(50) DEFAULT NULL COMMENT '红包奖励',
  status TINYINT(4) DEFAULT 1 COMMENT '0-弃用，1-可用',
  category INT(11) DEFAULT 1 COMMENT '类别',
  create_by VARCHAR(64) DEFAULT 'NULL' COMMENT '创建者',
  create_id VARCHAR(64) DEFAULT 'NULL' COMMENT '创建人ID',
  create_date DATETIME DEFAULT NULL COMMENT '创建时间',
  update_by VARCHAR(64) DEFAULT 'NULL' COMMENT '更新者',
  update_id VARCHAR(64) DEFAULT 'NULL' COMMENT '最后操作人ID',
  update_date DATETIME DEFAULT NULL COMMENT '更新时间',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标记（0：正常；1：删除）',
  remarks VARCHAR(255) DEFAULT 'NULL' COMMENT '备注信息',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '步数红包配置表';

--
-- Definition for table tomato_procedure_config
--
CREATE TABLE tomato_procedure_config (
  id VARCHAR(64) NOT NULL COMMENT 'id',
  award INT(11) DEFAULT 2000 COMMENT '配置步数奖励',
  category INT(11) DEFAULT 2 COMMENT '类别',
  description VARCHAR(50) DEFAULT '添加到小程序' COMMENT '添加到小程序',
  packet_count INT(9) DEFAULT 0 COMMENT '次数',
  remark VARCHAR(255) DEFAULT NULL COMMENT '预留字段',
  status TINYINT(4) DEFAULT 1,
  create_by VARCHAR(64) DEFAULT '' COMMENT '创建人ID',
  create_id VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  create_date DATETIME DEFAULT NULL COMMENT '创建时间',
  update_by VARCHAR(64) DEFAULT '' COMMENT '最近操作人ID',
  update_id VARCHAR(64) DEFAULT NULL COMMENT '最后操作人',
  update_date DATETIME DEFAULT NULL COMMENT '更新时间',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标记（0：正常；1：删除）',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '添加到小程序配置表';

--
-- Definition for table tomato_share_config
--
CREATE TABLE tomato_share_config (
  id VARCHAR(64) NOT NULL COMMENT 'id',
  award INT(11) DEFAULT 2000 COMMENT '配置步数奖励',
  category INT(11) DEFAULT 3 COMMENT '类别',
  description VARCHAR(50) DEFAULT '邀请好友' COMMENT '邀请好友',
  packet_count INT(9) DEFAULT 0 COMMENT '红包奖励次数',
  remark VARCHAR(255) DEFAULT NULL COMMENT '预留字段',
  status TINYINT(4) DEFAULT 1 COMMENT '0-弃用，1-可用',
  create_by VARCHAR(64) DEFAULT '' COMMENT '创建人ID',
  create_id VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  create_date DATETIME DEFAULT NULL COMMENT '创建时间',
  update_by VARCHAR(64) DEFAULT '' COMMENT '最近操作人ID',
  update_id VARCHAR(64) DEFAULT NULL COMMENT '最后操作人',
  update_date DATETIME DEFAULT NULL COMMENT '更新时间',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标记（0：正常；1：删除）',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '好友邀请配置表';

--
-- Definition for table tomato_sign_config
--
CREATE TABLE tomato_sign_config (
  id VARCHAR(64) NOT NULL COMMENT '主键',
  step INT(9) DEFAULT NULL COMMENT '任务配置的奖励步数',
  category INT(11) DEFAULT 4 COMMENT '类别',
  status TINYINT(1) DEFAULT 1 COMMENT '状态：1-正常，0-停用',
  description VARCHAR(255) DEFAULT NULL COMMENT '描述信息',
  count_day INT(9) DEFAULT NULL COMMENT '第几天',
  create_by VARCHAR(64) DEFAULT '' COMMENT '创建人ID',
  create_id VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  create_date DATETIME DEFAULT NULL COMMENT '创建时间',
  update_by VARCHAR(64) DEFAULT '' COMMENT '最近操作人ID',
  update_id VARCHAR(64) DEFAULT NULL COMMENT '最后操作人',
  update_date DATETIME DEFAULT NULL COMMENT '更新时间',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标记（0：正常；1：删除）',
  remarks VARCHAR(255) DEFAULT 'NULL' COMMENT '备注信息',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 2340
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '签到奖励配置表';

--
-- Definition for table tomato_user
--
CREATE TABLE tomato_user (
  id VARCHAR(64) NOT NULL COMMENT '主键',
  avatar VARCHAR(255) DEFAULT NULL COMMENT '头像链接',
  nick_name VARCHAR(255) DEFAULT NULL COMMENT '昵称',
  new_user TINYINT(4) DEFAULT 1 COMMENT '是否是新用户1：是',
  username VARCHAR(64) NOT NULL COMMENT '用户名-微信openId',
  lately_login DATETIME DEFAULT NULL COMMENT '最近登录时间',
  gold_history DECIMAL(10, 2) DEFAULT 0.00 COMMENT '金币累计',
  invite_user VARCHAR(64) DEFAULT NULL COMMENT '邀请者的openId',
  gold_today DECIMAL(10, 2) DEFAULT 0.00 COMMENT '今日赚得金币',
  register_date DATETIME DEFAULT NULL COMMENT '注册时间',
  gold DECIMAL(10, 2) DEFAULT 0.00 COMMENT '用户的总金币数',
  step INT(11) DEFAULT 0 COMMENT '用户每天通过活动获得的奖励步数，每日清0',
  source INT(11) DEFAULT 0 COMMENT '当前用户来源0：默认1：好友邀请',
  password VARCHAR(500) DEFAULT NULL COMMENT '密码',
  status INT(11) DEFAULT 0 COMMENT '当日是否用步数兑换金币0-未，1-有',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标记（0：正常；1：删除）',
  remarks VARCHAR(255) DEFAULT NULL COMMENT '备注信息',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci
COMMENT = '用户表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table tomato_user_address
--
CREATE TABLE tomato_user_address (
  id VARCHAR(64) NOT NULL COMMENT 'ID--shippingId',
  user_name VARCHAR(64) DEFAULT NULL COMMENT 'openid',
  real_name VARCHAR(64) DEFAULT NULL COMMENT '收货姓名',
  receiver_phone_no VARCHAR(32) DEFAULT NULL COMMENT '收货固定电话',
  receiver_mobile_no VARCHAR(64) DEFAULT NULL COMMENT '收货移动电话',
  province_id BIGINT(32) DEFAULT NULL COMMENT '收货人省ID',
  province_name VARCHAR(32) DEFAULT NULL COMMENT '省份',
  city_id BIGINT(20) DEFAULT NULL COMMENT '收货人城市ID',
  city_name VARCHAR(32) DEFAULT NULL COMMENT '收货人城市名称',
  district_name VARCHAR(32) DEFAULT NULL COMMENT '区/县',
  district_id VARCHAR(32) DEFAULT NULL COMMENT '区/县 编码',
  street_id VARCHAR(32) DEFAULT NULL COMMENT '街道ID',
  street_name VARCHAR(100) DEFAULT NULL COMMENT '接到名称',
  detail_address VARCHAR(200) DEFAULT NULL COMMENT '详细地址',
  receiver_zip_code VARCHAR(32) DEFAULT NULL COMMENT '邮编',
  default_address INT(1) DEFAULT 0 COMMENT '默认地址',
  create_by VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  create_date DATETIME DEFAULT NULL COMMENT '创建时间',
  update_by VARCHAR(64) DEFAULT NULL COMMENT '最近操作人',
  update_date DATETIME DEFAULT NULL COMMENT '更新时间',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标记（0：正常；1：删除）',
  remarks VARCHAR(255) DEFAULT NULL COMMENT '备注信息',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 3276
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
COMMENT = '地址信息表';

--
-- Definition for table tomato_user_day_buy
--
CREATE TABLE tomato_user_day_buy (
  id VARCHAR(64) NOT NULL COMMENT 'ID',
  status TINYINT(1) UNSIGNED DEFAULT 1 COMMENT '类别状态1-正常,2-已废弃',
  user_name VARCHAR(64) DEFAULT NULL COMMENT '用户的openId',
  amount INT(4) DEFAULT 0 COMMENT '用户每日购买数量',
  get_date DATETIME DEFAULT NULL COMMENT '用户当日购买商品时间',
  del_flag TINYINT(1) DEFAULT 0 COMMENT '删除标记',
  remarks VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '备注信息',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
COMMENT = '用户每日购买数量表';

--
-- Definition for table tomato_user_invite
--
CREATE TABLE tomato_user_invite (
  id VARCHAR(64) NOT NULL COMMENT 'id',
  user_name VARCHAR(64) DEFAULT NULL COMMENT '用户openId',
  insert_date DATETIME DEFAULT NULL COMMENT '插入当前奖励的时间',
  get_date DATETIME DEFAULT NULL COMMENT '用户领取奖励的时间',
  award INT(11) DEFAULT 2000 COMMENT '配置步数奖励',
  status TINYINT(4) DEFAULT 0 COMMENT '1-已经领取，0还未领取，默认0',
  description VARCHAR(50) DEFAULT '邀请好友' COMMENT '邀请好友',
  remark VARCHAR(255) DEFAULT NULL COMMENT '预留字段',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标记（0：正常；1：删除）',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '用户邀请奖励表';

--
-- Definition for table tomato_user_log
--
CREATE TABLE tomato_user_log (
  id VARCHAR(64) NOT NULL COMMENT '签到表id',
  user_name VARCHAR(64) DEFAULT NULL COMMENT 'openid',
  category_name VARCHAR(255) DEFAULT NULL COMMENT '类别名称',
  category INT(11) DEFAULT 0 COMMENT '类别',
  sign_date DATETIME DEFAULT NULL COMMENT '用户签到时期',
  award INT(11) DEFAULT 0 COMMENT '获得奖励',
  remark VARCHAR(255) DEFAULT NULL COMMENT '预留字段',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '用户日志表';

--
-- Definition for table tomato_user_packet
--
CREATE TABLE tomato_user_packet (
  id VARCHAR(64) NOT NULL COMMENT 'id',
  packet_count INT(9) DEFAULT 0 COMMENT '剩余红包领取次数',
  get_date DATETIME DEFAULT NULL COMMENT '红包领取时间',
  user_name VARCHAR(64) DEFAULT NULL COMMENT 'openid',
  remark VARCHAR(255) DEFAULT NULL COMMENT '预留字段',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标记（0：正常；1：删除）',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '签到奖励配置表';

--
-- Definition for table tomato_user_packet_log
--
CREATE TABLE tomato_user_packet_log (
  id VARCHAR(64) NOT NULL COMMENT 'id',
  award INT(9) DEFAULT 3 COMMENT '红包领取的奖励数',
  get_date DATETIME DEFAULT NULL COMMENT '红包领取时间',
  user_name VARCHAR(8) DEFAULT NULL COMMENT 'openid',
  remark VARCHAR(255) DEFAULT NULL COMMENT '预留字段',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标记（0：正常；1：删除）',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '红包领取日志表';

--
-- Definition for table tomato_user_procedure
--
CREATE TABLE tomato_user_procedure (
  id VARCHAR(64) NOT NULL COMMENT 'id',
  username VARCHAR(64) DEFAULT NULL COMMENT 'openId',
  packet_count INT(9) DEFAULT 1 COMMENT '次数',
  status TINYINT(4) DEFAULT 1,
  remark VARCHAR(255) DEFAULT NULL COMMENT '预留字段',
  complete_date DATETIME DEFAULT NULL COMMENT '用户完成时间',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标记（0：正常；1：删除）',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '添加到小程序配置表';

--
-- Definition for table tomato_user_sign
--
CREATE TABLE tomato_user_sign (
  id VARCHAR(64) NOT NULL COMMENT '签到表id',
  user_name VARCHAR(64) DEFAULT NULL COMMENT 'openid',
  sign_count INT(10) DEFAULT 0 COMMENT '用户连续签到次数',
  first_time TINYINT(4) DEFAULT 1 COMMENT '第一次签到1：是0：否',
  sign_date DATETIME DEFAULT NULL COMMENT '用户签到时期',
  update_date DATETIME DEFAULT NULL COMMENT '用户更新签到时间',
  auto_alert TINYINT(1) DEFAULT 0 COMMENT '是否自动提醒0-否1-是',
  remark VARCHAR(255) DEFAULT NULL COMMENT '预留字段',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '用户签到表';

--
-- Definition for table tomato_user_step
--
CREATE TABLE tomato_user_step (
  id VARCHAR(64) NOT NULL COMMENT 'id',
  status TINYINT(4) DEFAULT 0 COMMENT '1-今日已兑换，0-今日未兑换',
  step INT(11) DEFAULT 0 COMMENT '当前的允许兑换步数',
  symbol TINYINT(4) DEFAULT 0 COMMENT '事件标记位',
  gold DECIMAL(10, 2) DEFAULT NULL COMMENT '当前步数获得的金币',
  user_name VARCHAR(64) DEFAULT NULL COMMENT 'openid',
  order_no INT(11) NOT NULL AUTO_INCREMENT COMMENT '排序',
  exchange_date DATETIME DEFAULT NULL COMMENT '兑换金币时间',
  remark VARCHAR(255) DEFAULT NULL COMMENT '预留字段',
  PRIMARY KEY (id),
  INDEX order_no (order_no)
)
ENGINE = INNODB
AUTO_INCREMENT = 29
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '用户每日步数兑换表';

-- 
-- Dumping data for table tomato_activity_banner
--

-- Table company_business.tomato_activity_banner does not contain any data (it is empty)

-- 
-- Dumping data for table tomato_award_config
--

-- 
-- Dumping data for table tomato_cart_info
--

-- Table company_business.tomato_cart_info does not contain any data (it is empty)

-- 
-- Dumping data for table tomato_gold_log
--

-- 
-- Dumping data for table tomato_order_info
--

-- 
-- Dumping data for table tomato_packet_config
--

-- 
-- Dumping data for table tomato_procedure_config
--

-- 
-- Dumping data for table tomato_share_config
--

-- 
-- Dumping data for table tomato_sign_config
--

-- 
-- Dumping data for table tomato_user
--

-- Table company_business.tomato_user does not contain any data (it is empty)

-- 
-- Dumping data for table tomato_user_address
--

-- Table company_business.tomato_user_address does not contain any data (it is empty)

-- 
-- Dumping data for table tomato_user_day_buy
--

-- 
-- Dumping data for table tomato_user_invite
--

-- Table company_business.tomato_user_invite does not contain any data (it is empty)

-- 
-- Dumping data for table tomato_user_log
--

-- 
-- Dumping data for table tomato_user_packet
--

-- 
-- Dumping data for table tomato_user_packet_log
--

-- Table company_business.tomato_user_packet_log does not contain any data (it is empty)

-- 
-- Dumping data for table tomato_user_procedure
--

-- 
-- Dumping data for table tomato_user_sign
--

-- 
-- Dumping data for table tomato_user_step
--

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;